### ISSUE TITLE
Service geocode et basic auth

### ISSUE THREAD

**Issue by sylvainpolletvillard** [IGNF/geoportal-access-lib#15]
Bonjour,

La clé d'API que nous utilisions jusqu'ici pour le géocodage d'adresse ne semble pas fonctionner avec la nouvelle bibliothèque d'accès. Les requêtes de géocodage retournent ce genre de réponses:
`callback1468932596531({"http":{"status":302,"error":"<html><head><title>302 Found</title></head><body bgcolor=\"white\"><center><h1>302 Found</h1></center><hr><center>nginx</center></body></html>"}, "xml":null})`

En testant avec une autre clé (celle de la démo JSFiddle), tout fonctionne bien, on reçoit des statuts 200 et non plus 302.

Une hypothèse est que notre clé nécessite une authentification Basic Auth comme c'était le cas auparavant, mais je n'ai pas trouvé comment renseigner les credentials.
Savez-vous dans quel cas on est amenés à recevoir ces statuts 302, et si ça a un lien avec l'authentification ?

Merci d'avance

**Comment by gcebelieu** [comment]
Bonjour,

Cela est sans doute à rapprocher de cette issue : https://github.com/IGNF/geoportal-extensions/issues/31
Si votre clef est sécurisée par une authentification login/mdp, cela peut effectivement expliquer le HTTP 302 et l'authentification se fait bien en basic auth.

Au niveau de la bibliothèque d'accès, nous n'avons pas prévu de paramètres permettant de passer ces crédentials. C'est à réfléchir.

En attendant, je ne sais pas quel usage vous faites de la votre clef (SIG, application web ou application lourde) mais vous pouvez envisager un autre type de sécurisation (cf. http://api.ign.fr/tech-docs-js/fr/developpeur/geodrm.html#Clefs pour plus d'explications).

**Comment by sylvainpolletvillard** [comment]
Il s'agit d'une application web. Nous allons voir si passer par une sécurisation par referrer est envisageable, bien que cela pose quelques limitations pour nos environnements de test, notamment en local. Merci Gilles

**Comment by gcebelieu** [comment]
NB : on peut associer plusieurs referers à une même clef (séparés par une virgule)

**Comment by sylvainpolletvillard** [comment]
Nous sommes finalement passés sur une sécurisation par referrer.
