### ISSUE TITLE
X/Y inversé dans la réponse de géocodage

### ISSUE THREAD

**Issue by jfgigand** [IGNF/geoportal-access-lib#18]
Reproductible avec l'appel suivant :
`Gp.Services.geocode({
    apiKey : ".........",
    location : "17 RUE DE LA 87E DIVISION TERRITORIALE 35000 RENNES",
    filterOptions : {
      type : ["StreetAddress"]
    },
  onSuccess: .........
})`

Les X et Y sont inversés dans l'objet "position" de la réponse :

`{
    "locations": [
        {
            "position": {
                "x": 48.104007,
                "y": -1.643923
            },
            "matchType": "Street number",
            "placeAttributes": {
                "number": "17",
                "street": "r de la 87eme division territoriale",
                "municipality": "Rennes",
                "quality": "Plaque adresse",
                "ID": "ADRNIVX_0000000262194034",
                "department": "35",
                "bbox": {
                    "left": -1.643923,
                    "right": -1.643923,
                    "top": 48.104007,
                    "bottom": 48.104007
                },
                "commune": "Rennes",
                "insee": "35238",
                "territory": "FXX",
                "IDTR": "TRONROUT0000000047485244",
                "postalCode": "35000"
            },
            "type": "StreetAddress",
            "CLASSNAME": "DirectGeocodedLocation",
            "accuracy": 1
        }
    ]
}`

**Comment by lboulanger** [comment]
Bonjour,

Comme précisé dans [la documentation technique du service](http://ignf.github.io/geoportal-access-lib/v1.0.0-beta.1/jsdoc/module-Services.html#~geocode) : les coordonnées de la réponse du service de géocodage sont exprimées **par défaut** dans le système de coordonnées **EPSG:4326** (voir la définition XML sur http://epsg.io/4326). 
Dans ce système, les coordonnées sont exprimées en (lat,lon) et non (lon,lat) (l'ordre des axes n'est pas le même) : c'est pourquoi x=lat (abscisse) et y=lon (ordonnée).

Un autre système peut être spécifié, par exemple **CRS:84**, qui correspond à **EPSG:4326** mais avec l'ordre des axes inversé : coordonnées exprimées en (lon,lat). Il faut utiliser pour cela le paramètre **options.srs = "CRS:84"**.

Pour plus de détails :
- la structure de l'objet en sortie : http://ignf.github.io/geoportal-access-lib/v1.0.0-beta.1/jsdoc/Gp.Services.GeocodeResponse.html
- la structure de chaque objet du tableau "locations" : http://ignf.github.io/geoportal-access-lib/v1.0.0-beta.2/jsdoc/Gp.Services.Geocode.GeocodedLocation.html
- la structure de l'objet "position" de chaque localisation renvoyée : http://ignf.github.io/geoportal-access-lib/v1.0.0-beta.2/jsdoc/Gp.Point.html
