### ISSUE TITLE
Gp.Services.geocode() en XHR POST : mauvais Content-Type de la requête

### ISSUE THREAD

**Issue by jfgigand** [IGNF/geoportal-access-lib#19]
Un appel :
`Gp.Services.geocode({ protocol: "XHR", httpMethod: "POST" ...})`

provoque une requête XHR avec un body XML mais le header Content-Type reste à `application/x-www-form-urlencoded` au lieu de `text/xml`.

C'est sans doute la cause de la réponse 403, car une requête de géocodage en XHR GET fonctionne.

**Comment by gcebelieu** [comment]
Correctif présent sur master. Disponible dans la prochaine release.
