### ISSUE TITLE
Erreur Internet Explorer

### ISSUE THREAD

**Issue by hmouthier** [IGNF/geoportal-access-lib#2]
Bonjour
Un géocodage effectué sous Internet Explorer 11 ne fonctionne pas alors que ce même géocodage fonctionne sous chrome et firefox : 

```
Gp.Services.geocode({
    apiKey: APIkey,
    location : '5 r du 10 avril, 31400 Toulouse',
    maximumResponses : 1,
    onSuccess : function(locationGeocoded){
        console.log(locationGeocoded);
    }
}) ;
```

Il y a une absence de réponse de la part du onSuccess ou du onFailure, les erreurs du navigateur sont les suivantes : 

> TypeError: Object.keys : l’argument n’est pas un objet Object
> at i (https://github.com/IGNF/geoportal-access-lib/releases/download/v1.0.0-beta.1/GpServices.js:35:29058)
> at a.geocode (https://github.com/IGNF/geoportal-access-lib/releases/download/v1.0.0-beta.1/GpServices.js:37:13148)

**Comment by gcebelieu** [comment]
En effet, je reproduis le problème. On va regarder.

**Comment by lboulanger** [comment]
Bonjour,

Le problème a été identifié et corrigé : les sources ont été modifiées sur le dépôt geoportal-access-lib, et sont donc à nouveau fonctionnelles.
Il ne reste plus qu'à déployer la bibliothèque d'accès mise à jour.

**Comment by gcebelieu** [comment]
Ca marche. La version de dev, que l'on peut télécharger ici :

http://depot.ign.fr/geoportail/bibacces/develop/js/GpServices.js

intègre la correction.
