### ISSUE TITLE
comportement avec le paramètre rawResponse

### ISSUE THREAD

**Issue by gcebelieu** [IGNF/geoportal-access-lib#25]
sur la page : http://ignf.github.io/geoportal-access-lib/latest/jsdoc/tutorial-optimize-getconfig.html

on effectue un appel à Gp.Services.getConfig() avec le paramètre rawResponse==true

La requête envoyée est :

http://wxs.ign.fr/CLEF/autoconf?gp-access-lib=1.0.0-beta3&output=json&callback=callback1481722721680

et la réponse brute du service est :

callback1481722721680({"http":{"status":200,"error":null},"xml":"<?xml version=\"1.0\" encoding=\"UTF-8
\"?><ViewContext ..."});

Or, dans le callback onSuccess, la réponse est uniquement la partie "xml" de la réponse (sans la coquille jsonp). Est-ce normal (Pour moi le comportement attendu serait plutôt d'avoir l'intégralité de la réponse du service) ?.

**Comment by lowzonenose** [comment]
Pour la récupération du contenu de la réponse JSON, un correctif simple est à mettre en place afin d'avoir la structure suivante : 
> {"http":{"status":200,"error":null},"xml":"<ViewContext ..."}

Par contre, pour ce qui est de récupérer la réponse du service en JSONP, cad avec le _callback_, ça ne va pas être possible en l’état : 
> callback1481722721680({"http":{"status":200,"error":null},"xml":"<ViewContext ..."})

La réponse du service avec le _callback_ est appelée par la balise HTML script, et le code y est donc interprété du coté HTML..., on n'a donc pas la main dessus...

Il devrait être possible de contourner le mécanisme pour obtenir la réponse du service avec le callback en réalisant la requête en XHR avec une surcharge de l'url du service (options.ServerUrl) pour y passer des instructions JSONP (output=json)... À tester...

**Comment by gcebelieu** [comment]
Ok, je comprends le problème du callback.

Mon soucis est de restituer au mieux la réponse du service en fonction des paramètres en entrée mais sans introduire de mécanisme qui "reconstituerait" à postériori la réponse.

Si on peut retourner la coquille JSON fabriquée par le service avant qu'elle soit enlevée par la bibliothèque d'accès : OK
Si on doit refabriquer l'enrobage JSON(P) autour de la requête XHR : Non ce n'est pas le but.
