### ISSUE TITLE
nombre de points intermediaires max pour calcul itineraire?

### ISSUE THREAD

**Issue by smolleyes** [IGNF/geoportal-access-lib#28]
bonjour

tout est dans le titre 

combien de points intermediaires pouvons nous ajouter au calcul d itineraire au maximum ?

merci !

**Comment by lboulanger** [comment]
Bonjour,

Il n'y a pas a priori de limitation du nombre de points intermédiaires lors de l'interrogation du calcul d'itinéraire. Les points sont spécifiés dans un tableau viaPoints comme ci-dessous : 

```
Gp.Services.route({
	(...)
	 // points intermédiaires
	viaPoints : [
		{ x: 3, y: 46 },      
		{ x: 3.5, y: 46 }
	],
	(...)
});
```

**Comment by lowzonenose** [comment]
La seule limite possible serait la taille de l'URL en mode **GET** : 
[maximum length of HTTP GET request](https://stackoverflow.com/questions/2659952/maximum-length-of-http-get-request)
