### ISSUE TITLE
Géocodage inverse : paramètre srs non pris en compte

### ISSUE THREAD

**Issue by gcebelieu** [IGNF/geoportal-access-lib#29]
Je relaye un retour fait par mail (Marjorie) :

> suis en train d’utiliser l’API d’accès aux services et je rencontre un petit problème.
> Voici mon code (simplifié pour l’exemple) :
> 
> ```
> Gp.Services.reverseGeocode({
>             apiKey : Config.ignKey,
>             position : {                  
>               x: 170255.02920112704,
>               y: 5420630.171132063
>             },
>             maximumResponses:3,
>             srs:'EPSG:3857',
>             filterOptions : {
>                 type : ["PositionOfInterest"]
>             },
>             onSuccess : function (result) {
>                 console.log(result)
>             }
> 
>         });
> 
> ```
> Ma carte est en EPSG:3857, mais la requête produite est en 4326.
> 
> ```
> http://wxs.ign.fr/zzt9hj8nmsj1idy04kbk0pyi/geoportail/ols?output=json&qxml=<?xml version="1.0" encoding="UTF-8"?>
> <xls:XLS version="1.2"
> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xls="http://www.opengis.net/xls" xmlns:gml="http://www.opengis.net/gml" 
> xsi:schemaLocation="http://www.opengis.net/xls http://schemas.opengis.net/ols/1.2/olsAll.xsd">
> <xls:RequestHeader srsName="EPSG:4326"/>
> <xls:Request maximumResponses="3" methodName="ReverseGeocodeRequest" requestID="7754dfa9-3dfc-4f8a-9ef2-255fc191693b" version="1.2"><xls:ReverseGeocodeRequest returnFreeForm="false"><xls:Position><gml:Point xmlns:gml="http://www.opengis.net/gml"><gml:pos>5420630.171132063 170255.02920112704</gml:pos></gml:Point></xls:Position><xls:ReverseGeocodePreference>PositionOfInterest</xls:ReverseGeocodePreference></xls:ReverseGeocodeRequest></xls:Request>
> </xls:XLS>
> &callback=callback1489133912102  
> ```
> 
>
> J’ai l’impression que le paramètre srs n’est pas pris en compte :/

**Comment by lowzonenose** [comment]
Malheureusement, oui, le service de geocodage inverse ne reconnait que les projections suivantes : EPSG:4326 et CRS:84...
L'option *srs* permet juste de différencier le (lat,lon)avec EPSG:4326 vs (lon,lat) avec CRS:84 ...
La documentation est à mettre à jour !

**Comment by lowzonenose** [comment]
La documentation [développeur](http://ignf.github.io/geoportal-access-lib/latest/jsdoc/module-Services.html#~reverseGeocode) est à mettre à jour !
