### ISSUE TITLE
Erreur sur les "CadastralParcels"

### ISSUE THREAD

**Issue by ThomasG77** [IGNF/geoportal-access-lib#3]
J'ai un erreur 403 lorsque je tente d'utiliser les services `Gp.Services.geocode` et `Gp.Services.reverseGeocode` en utilisant l'option "CadastralParcels". Le service renvoie une erreur 403 avec le message `<ExceptionReport><Exception exceptionCode="MissingRights">No rights for this ressource or ressource does not exist</Exception></ExceptionReport>` Je ne sais pas si c'est le service ou les appels via l'API qui sont en cause.

Je ne pense pas que ce soit un problème de droits malgré le message: la clé générée utilisée supporte les appels "parcelles cadastrales" car elle a été testée avec le point d'entrée OpenLS référencé sur http://api.ign.fr/tech-docs-js/fr/webmaster/layers.html#Types_de_services

Merci de m'indiquer si vous arrivez à reproduire.

**Comment by gcebelieu** [comment]
Pouvez-vous indiquer l'appel exact que vous faites de Gp.Services.geocode.

Eventuellement la requête qui part vers le service si vous pouvez l'intercepter avec votre navigateur.

**Comment by ThomasG77** [comment]
Bonsoir,

Je clôture. Je viens de voir où est l'erreur et j'ai ouvert une PR en ce sens pour corriger.

Elle est partiellement liée à moi mais aussi à une faute de frappe ou étourderie au choix dans votre documentation. Celle sur [le dépôt](https://github.com/IGNF/geoportal-access-lib#obtenir-des-localisants-toponymes-adresses-parcelles-cadastrales-proches-dune-position-donn%C3%A9e-g%C3%A9ocodage-inverse) parle de "CadastralParcels" mais en fait, il faut utiliser "CadastralParcel" (noté l'absence de s) comme la documentation déjà existante sur http://api.ign.fr/tech-docs-js/fr/developpeur/search.html#Recherche_par_parcelles_cadastrales le mentionne et en cherchant un peu [l'API actuelle](http://ignf.github.io/geoportal-access-lib/v1.0.0-beta.1/jsdoc/module-Services.html#~geocode) est également correcte.
