### ISSUE TITLE
Compilation sous Windows

### ISSUE THREAD

**Issue by gcebelieu** [IGNF/geoportal-access-lib#32]
Tester et voir ce qu'il est nécessaire pour faire fonctionner la compilation sous Windows de la bibliothèque d'accès.

Cf. https://github.com/IGNF/geoportal-extensions/issues/119

**Comment by lowzonenose** [comment]
# Installation des outils

* nodeJS (https://nodejs.org/en/download/)
* git (https://git-scm.com/downloads)
* git gui
* tortoiseGit (par exemple)
* Visual Studio Code (VSCode) (par exemple)


## Réglage des outils

### Gestion des fins de lignes (Git)

**ouvrir une console**

    git config core.autocrlf false
    git config core.safecrlf=true
    git rm --cached -r
    git reset --hard

Note :
Possibilité de le faire via l'editeur _Visual Studio Code_ dans le menu
_Fichier > Préférences > Paramètres utilisateurs_
Pour plus d'information, cf. https://code.visualstudio.com/docs/getstarted/settings

### Configuration du proxy d'entreprise

**ouvrir une console**

    npm config set proxy http://proxy.company.com:8080
    npm config set https-proxy http://proxy.company.com:8080

ou

modifier le fichier _C:\Users\<USER>\.npmrc_ avec les lignes suivantes :

    proxy=http://proxy.company.com:8080
    https-proxy=http://proxy.company.com:8080
    https_proxy=http://proxy.company.com:8080

## Utilisation du terminal (Console Git ou NodeJS)

**Git** et **NodeJS** fournissent leur propre console.
L'utilisation de ces consoles permet d'avoir un environnement complet (ex. variables systèmes),
mais il est tout à fait possible d'utiliser la console de windows (CMD).

Note :
Possibilité d'utiliser le terminal de _Visual Studio Code_ dans le menu
_Affichage > Integred Terminal_
Pour plus d'information, cf. https://code.visualstudio.com/docs/editor/integrated-terminal

# Fork du dépot de sources

Avec votre client git (par exemple tortoiseGit)

# Compilation du projet

## NPM

**ouvrir une console**

    npm install

Note :
Si votre connexion ne permet pas de télécharger _PhantomJS_, il est possible de
le récuperer sur cette URL : http://phantomjs.org/download.html
Puis, relancer l'installation...

Attention :
Pour installation manuelle, ne pas oublier de mettre l'executable _phantomjs.exe_
dans l'environnement d'execution de windows (ex. https://www.java.com/fr/download/help/path.xml)

## GULP

**ouvrir une console**

    gulp

### Erreur de fin de lignes

Si vous avez des erreurs de parsing tel que **Invalid line break**, vous devez
modifier le paramètre du fichier _.jscs_ :
> validateLineBreaks : { character : "CRLF" }

### Execution de la JSDOC

Sous Windows, il est possible que la JSDoc ne soit pas compilée correctement
(problème de path du binaire), on peut l'executer manuellement :

**ouvrir une console**

    node_modules\.bin\jsdoc -c jsdoc.json

### Publication

**ouvrir une console**

    gulp publish

# Execution des exemples

**ouvrir une console**

    gulp server-samples

Le navigateur s'ouvre sur la page des exemples sur l'URL suivante :
http://localhost:9001/samples/index-samples.html

# Execution des tests

**ouvrir une console**

    gulp server-test

Le navigateur s'ouvre sur la page des tests sur l'URL suivante :
http://localhost:9001/test/index.html

## En mode developpement

**ouvrir une console**

    gulp watch

Le navigateur s'ouvre sur la page des tests sur l'URL suivante :
http://localhost:9001/test/index.html

Note :
Chaque modification des tests va recharger cette page automatiquement...

**Comment by lowzonenose** [comment]
Remarques sur la compilation sous Windows à placer dans le fichier COMPILE.md

**Comment by gcebelieu** [comment]
OK, à intégrer dans le COMPILE.md
