### ISSUE TITLE
Le protocole JSONP ne passe pas en mode "NodeJS"

### ISSUE THREAD

**Issue by gcebelieu** [IGNF/geoportal-access-lib#33]
Lorsqu'on utilise la bibliothèque d'accès en mode NodeJS (ie : pas dans un browser), l'appel aux fonctions Gp.Services.xxx() plante si on reste en protocole JSONP.

En effet, pour ce protocole, on utilise plusieurs fois l'objet window. Per exemple ici :  https://github.com/IGNF/geoportal-access-lib/blob/master/src/Protocols/JSONP.js#L181 et l'objet window n'existe pas en mode NodeJS.

Il faudrait remplacer ces utilisations par des fonctions équivalente supportées par Node. 

Exemple pour setTimeout : http://www.java2s.com/Tutorials/Javascript/Node.js_Tutorial/0270__Node.js_setTimeout_setInterval.htm

A rapprocher de #30 ...

**Comment by lowzonenose** [comment]
On peut interdire l'utilisation du protocole **JSONP** sur un environnement **NodeJS** , et forcer la bascule dans le protocole **XHR**...
cf.  _src/Protocols/Protocol.js_
```
// on determine l'environnement d'execution : browser ou non ?
// et on bascule sur le protocole XHR pour nodeJS...
if ( typeof window === "undefined" && this.options.protocol === "JSONP") {
  this.options.protocol = "XHR";
}
```

On peut aussi lancer une **exception** : 
```
// on determine l'environnement d'execution : browser ou non ?
// et on lance une exception sur l'utilisation du protocole JSONP pour nodeJS...
if ( typeof window === "undefined" && this.options.protocol === "JSONP") {
  throw new Error(_.getMessage("PARAM_NOT_SUPPORT", "protocol=JSONP"));
}
```
Sortie : 

> Error: Value(s) for parameter(s) 'protocol=JSONP' not supported

**Comment by gcebelieu** [comment]
Hum... je serais plus pour de la transparence : 

1. si l'objet windows n'existe pas, sortir en erreur et mettre un message clair dans la console indiquant qu'il faut utiliser le protcole XHR à la place.

2. Indiquer dans la doc utilisateur + jsdoc que le protocole JSONP ne fonctionne pas en mode non browser.

**Comment by lowzonenose** [comment]
> Error: Value(s) for parameter(s) 'protocol=JSONP (instead use XHR)' not supported to NodeJS

**Comment by gcebelieu** [comment]
Le dernier commit fait parfois du reroutage en douce sur XHR : il vaut mieux lever une erreur lorsqu'on croise l'objet Windows et sortir proprement. 

Cf. commentaire : 

https://github.com/IGNF/geoportal-access-lib/commit/23e1eb218a9e37514391f3d9b248927fa07dcdbe#commitcomment-22786105
