### ISSUE TITLE
Gp.Protocols.XHR - crash IE en raison d'un appel Object.keys sur une chaîne de caractères

### ISSUE THREAD

**Issue by mborne** [IGNF/geoportal-access-lib#38]
En appellant le service d'autocomplétion, on rencontre une erreur sous IE11 qui indique que Object.keys est appelé sur un élément qui n'est pas de type "object"

En descendant dans les appels, on remarque que le problème est dans la fonction XHR.__call : 

https://github.com/IGNF/geoportal-access-lib/blob/v1.0.0/src/Protocols/XHR.js#L155

La données présente dans options.data est une chaîne de caractères. Exemple : "text=la&type=StreetAddress,PositionOfInterest&terr=&maximumResponses=150".

**Comment by gcebelieu** [comment]
OK, je reproduis l'erreur.

Apparemment, La ligne de code fautive a été introduite par la PR #23 (https://github.com/IGNF/geoportal-access-lib/commit/d9ec2ccef7f9038f1c85ee35e71d8191f41d2c6c)

On regarde ça rapidement.

**Comment by gcebelieu** [comment]
@lboulanger peux-tu te pencher sur le PB ?

**Comment by lboulanger** [comment]
Normalement, le problème devrait être corrigé par le commit suivant : 94d932c

**Comment by gcebelieu** [comment]
La nouvelle version [1.0.1](https://github.com/IGNF/geoportal-access-lib/releases/tag/v1.0.1) embarque ce correctif.
