### ISSUE TITLE
Contribution (howto)

### ISSUE THREAD

**Issue by lowzonenose** [IGNF/geoportal-access-lib#40]
Contribuer
==========

## Liens utiles

https://help.github.com/categories/collaborating-with-issues-and-pull-requests/

avec les liens les plus utiles :

  https://help.github.com/articles/configuring-a-remote-for-a-fork/
  https://help.github.com/articles/syncing-a-fork/
  https://help.github.com/articles/about-pull-requests/
  https://help.github.com/articles/creating-a-pull-request/
  https://help.github.com/articles/checking-out-pull-requests-locally/
  https://help.github.com/articles/merging-a-pull-request/
  https://help.github.com/articles/about-pull-request-merges/
  https://help.github.com/articles/interactive-rebase

Un exemple de contribution sur un projet (en français) :
https://git-scm.com/book/fr/v2/GitHub-Contribution-%C3%A0-un-projet 

## Ouverture d'un ticket (issue)

Vous devez ouvrir un ticket dans les situations suivantes :

* Signaler une erreur que vous ne pouvez pas résoudre vous-même
* Discuter d'un sujet ou d'une idée
* Proposer une nouvelle fonctionnalité ou une autre idée de projet

Votre ticket est ensuite pris en compte par les membres de l'équipe ou de la communauté.
Et une action peut vous être demandée telle qu'**ouvrir un Pull Request** afin de contribuer...

## Ouvrir un pull request (PR)

Voici comment soumettre un **pull request** !

### On «fork» le projet

- Créez un `fork` du projet sur le Github.
- Cloner le en local. Ce `dépôt distant` sur le Github s'appelle `origin`.
- Ajoutez le dépôt d'origine en tant que `dépôt distant` avec le mot cléf : `upstream` (cf. https://help.github.com/articles/configuring-a-remote-for-a-fork/).
- Si vous avez créé votre `fork` il y a quelque temps, assurez-vous de récupérer les modifications dans votre dépôt local (cf. https://help.github.com/articles/syncing-a-fork/).
- Récupérez les modification le plus souvent possible de "upstream" afin d'être le plus à jour possible, de sorte que lorsque vous soumettez votre demande (PR), les conflits de fusion seront plus faciles à résoudre !

### On code...

- Créez une `nouvelle branche` pour travailler. Nommez la par exemple avec le nom de la fonctionnalité à implementer (ex. feature-tests-myfunction) ou celui de l'issue qu'elle vise à résoudre (ex. feature-issue-xx)
- Implémentez, corrigez, écrivez votre `code`.
- Suivez le `style` de code du projet, (ex. l'indentation).
- Si le projet possède des `tests`, exécutez-les !
Que des tests existent ou non, assurez-vous que vos modifications ne cassent pas le projet existant !
- Écrivez ou adaptez les `tests` au besoin.
- Ajoutez ou modifiez la `documentation` au besoin.
- `Squash` vos commit en un seul avec le `rebase interactif` (cf. https://help.github.com/articles/interactive-rebase). 
- Poussez cette branche sur votre dépôt, sur le dépôt marqué `origin`.

### On soumet une PR...

- De votre `fork`, ouvrez une demande de `pull request` sur cette branche (cf. https://help.github.com/articles/creating-a-pull-request/). Et ciblez sur la branche `master` du dépôt d'origine...
- Référencez tous les problèmes ainsi que la documentation sur votre PR.
- Utilisez dans vos `commit` des fonctionnalités de GitHub (ex. "Fix #37.").
- Si le responsable demande des modifications supplémentaires, il suffit de les pousser vers votre branche locale, le `pull request` se met à jour automatiquement.
- Une fois que le `pull request` est approuvé, le responsable le fusionnera ou vous demandera de le faire si vous avez les droits (cf. https://help.github.com/articles/merging-a-pull-request/).

**Comment by lowzonenose** [comment]
Quelque chose de simple..., des directives pour _forker_ le projet, coder et soumettre sa contribution...
Ceci est à placer dans le fichier **CONTRIBUTING.md** ou **CONTRIBUTE.md**

**Comment by gcebelieu** [comment]
j'ai fait quelques petits correctifs dans le texte.

Je suggère de rajouter les liens de la doc github correspondante au fur et à mesure de nos instructions plutôt que de tout mettre au début en vrac.

**Comment by sylvainpolletvillard** [comment]
Bonjour,

Voici mes retours sur le tutoriel:
- comme indiqué par @lowzonenose , ce tutoriel est à placer dans un fichier CONTRIBUTING.md à la racine du repo : https://github.com/blog/1184-contributing-guidelines
- pour le squash de commits en un seul, je n'utilise pas de rebase mais un soft reset sur la HEAD, tel que décrit ici : https://gist.github.com/patik/b8a9dc5cd356f9f6f980 ; je trouve ça personnellement beaucoup plus simple, et cela permet de synchroniser le fork avec les modifications distantes au passage.
- il faudrait mentionner dans ce guide le linter et l'outil de test utilisés, ainsi que les commandes pour les lancer. J'ai l'habitude de gulp donc j'ai épluché le gulpfile pour voir ce que vous utilisiez, mais un débutant n'aura pas ce réflexe.
- ma PR a été retardée par une demande de commentaires dans les sections générant automatiquement de la JSDoc. Ce serait bien de documenter cette fonctionnalité quelque-part dans le guide.

**Comment by lboulanger** [comment]
Merci beaucoup @sylvainpolletvillard pour ce retour ! :+1:  
Notamment pour les points auxquels nous n'avions pas pensé ! (JSDoc et commandes à lancer pour tester et vérifier le code), que nous allons rajouter.
Bonne journée !
