### ISSUE TITLE
L'autocomplétion ne fonctionne pas avec certains codes département INSEE

### ISSUE THREAD

**Issue by ojathelonius** [IGNF/geoportal-access-lib#45]
Un appel à Gp.Services.autoComplete ne fonctionne pas avec certains codes INSEE tels que ceux de la Corse (2A et 2B) ainsi que les DROM tel que présenté ci-dessous.

```javascript
var filter = {
    "territory": ['2A', '2B']
};

var options = {
    text: text,
    apiKey: api_key,
    filterOptions: filter,
    onSuccess: callback,
    onFailure: error,
    protocol: 'XHR'
};

// Pas de résultats quel que soit le texte entré
Gp.Services.autoComplete(options);
```

Le service semble toujours utiliser les anciens codes INSEE, puisque dans le cas de la Corse, utiliser "20" à la place de "2A" ou "2B" règle le problème.

**Comment by gcebelieu** [comment]
Bonjour, 

Je confirme la nom prise en compte des valeurs "2A" et "2B", mais celle de la valeur "20" pour le filtrage. C'est malheureusement du à une limitation actuelle du [service web d'autocomplétion](https://geoservices.ign.fr/documentation/geoservices/autocompletion.html) sous-jacent. A voir si cela peut être corrigé à l'avenir (mais indépendamment de ce projet).

Pour les DROM, je ne reproduis pas le problème : le filtrage marche bien avec les codes insee des départements d'outre-mer. Par exemple : "974" pour la Réunion. Pouvez-vous indiquer des valeurs qui ne marchent pas pour vous ?

NB : j'ai mis à jour l'exemple jsfiddle avec des valeurs témoins : http://jsfiddle.net/ignfgeoportail/jsjqk4wq/embedded/result,js,html,css/

**Comment by ojathelonius** [comment]
Etrange, je n'ai plus ce problème sur les DROM, ce devait être une erreur de ma part.

Merci de votre réponse !
