### ISSUE TITLE
Type incorrect pour totalDistance sur le retour de Gp.Services.route() 

### ISSUE THREAD

**Issue by o-bo** [IGNF/geoportal-access-lib#48]
La [doc](http://ignf.github.io/geoportal-access-lib/latest/jsdoc/Gp.Services.RouteResponse.html) précise que totalDistance est un float exprimant la valeur en m ou en km en fonction de l'unité passée.

Le retour de l'appel renvoie une chaîne de caractères formatée avec la valeur et l'unité (ex: '2.9 km').

**Comment by lboulanger** [comment]
Bonjour,

En effet, il y a une incohérence entre la documentation et le fonctionnement de Gp.Services.route().
Il y a aussi deux comportements différents selon la valeur du paramètre "distanceUnit" en entrée : 

- si `distanceUnit="km"` (valeur par défaut) : totalDistance est bien une chaîne de caractères formatée avec la valeur et l'unité (ex. "19.6 Km")
- si `distanceUnit="m"` : totalDistance est une chaîne de caractères qui contient uniquement la valeur (en mètres, ex. "19599.14").

Idéalement, il faudrait modifier ce comportement, mais cette modification pourrait avoir des impacts importants sur les applications qui utilisent déjà ce paramètre...

En attendant, j'ai modifié la documentation : 
`@property {String} totalDistance - Length of the route. If distanceUnit parameter was set to "km" (default), totalDistance is a string containing the total distance expressed in kilometers, followed by " Km" (e.g. : "19.6 Km"). If distanceUnit parameter was set to "m", totalDistance is a string containing the total distance expressed in meters (e.g. : "19599.14").`

La modification apparaîtra [dans la documentation en ligne](http://ignf.github.io/geoportal-access-lib/latest/jsdoc/Gp.Services.RouteResponse.html) lors de la prochaine release de la bibliothèque d'accès.

**Comment by lowzonenose** [comment]
Doc. livrée...
