### ISSUE TITLE
Route service : avoir la geometrie des instructions séparément de la géométrie globale

### ISSUE THREAD

**Issue by gcebelieu** [IGNF/geoportal-access-lib#5]
La fonction Gp.Services.route ne permet d'obtenir un itinéraire dont la géométrie est seulement globale. Les instructions de navigation ne sont liées à aucune géométrie ce qui rend impossible la liaison d'une instruction avec sa représentation géométrique.

Le service web utilisé permet de moduler cela en utilisant le paramètre "format". Il faudrait donc :
- rajouter la prise en compte de ce paramètre dans la requête
- modifier la structure de RouteResponse pour prendre en compte les informations supplémentaires.

**Comment by lowzonenose** [comment]
Ajout de l'option 'provideGeometry' sur le service de calcul d’itinéraire. 
Si 'provideGeometry=true', la géométrie est associée aux instructions de navigations.

**Comment by gcebelieu** [comment]
OK.
Il faudrait rajouter la documentation des informations supplémentaires dans les instructions dans la jsdoc pour la classe de réponse :  Gp.Services.Route.RouteInstruction
