### ISSUE TITLE
JSONP : nettoyage de la balise script lors d'un timeout

### ISSUE THREAD

**Issue by gcebelieu** [IGNF/geoportal-access-lib#6]
Lorsqu'on envoie une requête sur un webservice et que le timeout est atteint, il faut supprimer la balise <script> générée pour ne pas que la réponse soit traitée si elle arrive après le timeOut.

**Comment by lowzonenose** [comment]
Nettoyage des tags issus du **JSONP** dans la page après un **TimeOut** du service.
