### ISSUE TITLE
autoconf en local ne fonctionne pas sur Chrome

### ISSUE THREAD

**Issue by khamphon** [IGNF/geoportal-access-lib#64]
Bonjour,

J'ai suivi le tuto dispo ici "http://ignf.github.io/geoportal-access-lib/latest/jsdoc/tutorial-optimize-getconfig.html" afin d'utiliser le fichier d'autoconf embarqué dans notre application.
Les tests sur nos environnement local fonctionne très bien.

Par contre lorsque nous déployons l'appli sur nos serveurs de production, la carto ne s'affiche plus et nous avons cette erreur :
########################
core.js?4dd3:1598 ERROR Error: Uncaught (in promise): ErrorService: The service returned an exception : 'Erreur lors de la lecture de la réponse : elle n'est pas au format attendu.
(raw response service'<body xmlns="http://www.w3.org/1999/xhtml"><parsererror style="display: block; white-space: pre; border: 2px solid #c77; padding: 0 1em 0 1em; margin: 1em; background-color: #fdd; color: black"><h3>This page contains the following errors:</h3><div style="font-family:monospace;font-size:12px">error on line 1 at column 1: Document is empty
</div><h3>Below is a rendering of the page up to the first error.</h3></parsererror></body>')'
Error
    at new ErrorService (GpPluginOl3-src.js:954)
    at Object.build (GpPluginOl3-src.js:3671)
    at AutoConf.analyzeResponse (GpPluginOl3-src.js:3819)
    at AutoConf.onCallService (GpPluginOl3-src.js:1310)
    at onResponse (GpPluginOl3-src.js:1394)
    at GpPluginOl3-src.js:758
    at ZoneDelegate.invoke (zone.js?6524:388)
    at Object.onInvoke (core.js?4dd3:4062)
    at ZoneDelegate.invoke (zone.js?6524:387)
    at Zone.run (zone.js?6524:138)
    at new ErrorService (GpPluginOl3-src.js:954)
    at Object.build (GpPluginOl3-src.js:3671)
    at AutoConf.analyzeResponse (GpPluginOl3-src.js:3819)
    at AutoConf.onCallService (GpPluginOl3-src.js:1310)
    at onResponse (GpPluginOl3-src.js:1394)
    at GpPluginOl3-src.js:758
    at ZoneDelegate.invoke (zone.js?6524:388)
    at Object.onInvoke (core.js?4dd3:4062)
    at ZoneDelegate.invoke (zone.js?6524:387)
    at Zone.run (zone.js?6524:138)
    at resolvePromise (zone.js?6524:814)
    at eval (zone.js?6524:877)
    at ZoneDelegate.invokeTask (zone.js?6524:421)
    at Object.onInvokeTask (core.js?4dd3:4053)
    at ZoneDelegate.invokeTask (zone.js?6524:420)
    at Zone.runTask (zone.js?6524:188)
    at drainMicroTaskQueue (zone.js?6524:595)
    at ZoneTask.invokeTask [as invoke] (zone.js?6524:500)
    at invokeTask (zone.js?6524:1540)
    at XMLHttpRequest.globalZoneAwareCallback (zone.js?6524:1566)

########################

Pour information, le problème ne se produit que sur Chrome.

Merci de votre retour

**Comment by lboulanger** [comment]
Bonjour,

Les fichiers utilisés en local et production sont-ils exactement les mêmes ?

Pourriez-vous nous donner un aperçu du code permettant d'utiliser le fichier autoconf, et celui permettant de charger la carte ?
Et si possible, un aperçu du tout début du fichier autoconf.json que vous appelez ?

Ou même idéalement : si vous pouvez nous donner une url où votre application est déployée, afin que nous puissions essayer de comprendre ce qui ne va pas ? 

C'est particulièrement surprenant que le problème ne se produise que sur Chrome. Peut-être une question de cache sur l'un des navigateurs ? Avez-vous essayé en navigation privée ?

**Comment by khamphon** [comment]
Bonjour,

Pour l'instant nous sommes en test sur notre environnement de pré-production.
Le fichier autoconf est exactement le même que celui de dév.

Voici le code utilisé pour initialiser l'autoconf : 
`
    initConfig: function() {
		return this.lazyLoadCartographieLibs().then(() => {
			if(Gp.Config != null) {
				return Promise.resolve(Gp.Config);
			}
			return new Promise((resolve, reject) => {
				Gp.Services.getConfig({
					serverUrl: "autoconf.json",
                                        callbackSuffix: "", 
					onSuccess: resolve,
					onFailure: reject
				});
			});
		});
	},
`

Le fichier autoconf qu'on utilise commence par : 
`
callback({"http":{"status":200,"error":null},"xml":"<?xml version=\"1.0\" encoding=\"UTF-8\"?><ViewContext xmlns=\"http://www.opengis.net/context\" xmlns:gpp=\"https://api.ign.fr/geoportail\" xmlns:ows=\"http://www.opengis.net/ows/1.1\" xmlns:sld=\"http://www.opengis.net/sld\" xmlns:wmts=\"http://www.opengis.net/wmts/1.0\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" id=\"autoConf\" version=\"1.1.0\" xsi:schemaLocation=\"http://www.opengis.net/context https://gpp3-wxs.ign.fr/schemas/extContext.xsd https://api.ign.fr/geoportail https://wxs.ign.fr/schemas/autoconf/autoconf.xsd\"><General> ...
`

Merci d'avance de votre aide.

Cordialement,

**Comment by lowzonenose** [comment]
Peut-être un conflit sur les promises avec celles de Angular (https://github.com/angular/zone.js/)..., à creuser de ce côté...

**Comment by khamphon** [comment]
Bonjour,

Je reviens vers vous pour vous demander encore du support.
Après plusieurs essais voici l'erreur que j'ai maintenant dans ma console : 
`Refused to execute script from 'http://[URL_SERVEUR]/autoconf-dev.json?gp-access-lib=1.1.0&output=json&callback=callback' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.`

Le code utilisé est celui-ci : 
`Gp.Services.getConfig({
    serverUrl: "http://[URL_SERVEUR]/autoconf-dev.json",
    callbackSuffix: "",
    contentType: "application/json",
    onSuccess: resolve,
    onFailure: reject
});`

Le problème est également présent sur firefox.

Merci de votre aide.

**Comment by khamphon** [comment]
La solution a été de renommer le fichier autoconf.json en autoconf.js.
