### ISSUE TITLE
Couche Plan IGN V2 - Fond noir à la place de blanc

### ISSUE THREAD

**Issue by khamphon** [IGNF/geoportal-access-lib#72]
Bonjour,

Depuis que nous sommes passé sur la nouvelle couche GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2, lorsque nous appelons le webservice wms, l'image retournée contient du noir plutôt que du blanc.
Voici la requête que nous appelons :
https://wxs.ign.fr/__CLE_IGN__/geopo...256&HEIGHT=256

Le format de l'image en JPG est obligatoire chez nous car le format PNG est trop lourd.
Mais même en passant par du PNG, il y a du noir au lieu du blanc.

Je vous remercie d'avance de votre aide.

Cordialement,

**Comment by elias75015** [comment]
Bonjour

La donnée PLANIGNV2 a été republiée le 26/08/2020, sans transparence. Le problème de noir à la place de la transparence venait effectivement du JPEG. En PNG, si votre cl/ient ne gèrait pas la transparence, du noir s'affichait également.
